Travis: Remove homebrew installation for mac
Travis says

    Error: The `brew link` step did not complete successfully
    The formula built, but is not symlinked into /usr/local
    Could not symlink include/c++
    Target /usr/local/include/c++
    already exists. You may want to remove it:
      rm '/usr/local/include/c++'
    To force the link and overwrite all conflicting files:
      brew link --overwrite gcc
    To list all files that would be deleted:
      brew link --overwrite --dry-run gcc
    Possible conflicting files are:
    /usr/local/include/c++ -> /usr/local/Caskroom/oclint/0.11,15.6.0/oclint-0.11/include/c++
    ==> Summary
    🍺  /usr/local/Cellar/gcc/7.2.0: 1,487 files, 284MB
    The command "if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi" failed and exited with 1 during .

I'm hoping this will fix that, since it looks like we already have
some gcc installed. If it doesn't, I'll revert and try the `--overwrite`
version.